### ISSUE TITLE
[TEOTB-22][DEV-OPS] Delete snapshots versions after release or more 3.

### ISSUE THREAD

**Issue by DonkeyRit** [DonkeyRit/friendly-spoon#37]

**Comment by DonkeyRit** [comment]
# Github Actions 

When I tried to use **_Personal Access Token_** I revealed a strange behaviour. It is important to specify the following settings for checkout step.

```
- uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
```
